# Generated by Django 3.1.7 on 2021-03-29 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 11, 54, 552498)),
        ),
    ]
